### ISSUE TITLE
CrossOver 21 update

### ISSUE THREAD

**Issue by 2b** [Gcenx/homebrew-wine#24]
Codeweavers released [CrossOver 21 sources](https://media.codeweavers.com/pub/crossover/source/crossover-sources-21.0.0.tar.gz) based on Wine 6.0. Do you have any plans to update your wine-crossover?

Thank you.

**Comment by Gcenx** [comment]
I've already updated my sources mirror https://github.com/Gcenx/winecx/commit/47e3fed8a5fde3d370209c9c8bbcd3ac5b370588  
The problem is CX21 being based on wine-6.0 still contains some additional annoying regressions like .Net not functioning.

After all the testing I've done since the sources landed I'm not sure it's worth updating the current rather stable package.

**Comment by 2b** [comment]
Thanks for the answer, I was trying to figure out is there any reason to dive into compiling new version by myself, if you aren't going to update binaries. As I see it now, it doesn't seem worth it.
