### ISSUE TITLE
Double-clicking on (32 bit) foo.exe fails to launch it but `wine foo.exe` in terminal works great. Expected?

### ISSUE THREAD

**Issue by fiendish** [Gcenx/homebrew-wine#28]
After installing `brew install --cask --no-quarantine gcenx/wine/wine-crossover`
When I doubleclick on my 32-bit windows exes, "Wine Crossover.app" launches and then just exits right away without any messages.

If I launch them with `wine foo.exe` in the terminal though everything works properly because that appears to force using wine32on64.

Is it expected that using the app doesn't know when to use wine32on64?
(is wine32on64 even still needed in preference to wine64 anymore? I just ran wine64 on my 32 bit exe and it seems to run fine with the crossover21 release?)

(Thank you by the way for the crossover21 release. It works _muuuch_ more smoothly than the crossover20 version.)

**Comment by Gcenx** [comment]
> After installing `brew install --cask --no-quarantine gcenx/wine/wine-crossover` When I doubleclick on my 32-bit windows exes, "Wine Crossover.app" launches and then just exits right away without any messages.

I don't use this function so didn't know if it was working or not .

> If I launch them with `wine foo.exe` in the terminal though everything works properly.

That's expected to work due to the included wrapper script, the script makes it simpler on modern macOS and enables being able to use winetricks with ease.

> Is it expected that using the app directly doesn't know how to find its own 32on64 translator? Would it be possible to swap the internal wine bin with your wrapper script?

It's possible the app bundles `wine` binary attempts to still use `/Contents/Resources/wine/bin/wine`, I had compiled this rather a while ago so unable to recall. Having `wine` use the wrapper script could cause other issues thanks to SIP.

I believe the large majority of users are running macOS Catalina or later so it might make more sense to force `wine32on64` to be `wine` and drop the wrapper script. Then bump the cask to require macOS Catalina and later.

Instead of waiting on me hacking away at the sources you could try to replace `wine` & `wine-preloader` with `wine32on64` and `wine32on64-preloader` that should get the "Open With" function working.

> (Thank you by the way for the crossover21 release. It works _muuuch_ more smoothly than the crossover20 version.)

:)

**Comment by Gcenx** [comment]
This should be resolved by the new rebuild https://github.com/Gcenx/homebrew-wine/commit/f5ba54dd225b98873f7eada2434ef151c3c07497

**Comment by fiendish** [comment]
Confirmed. Thanks!
