### ISSUE TITLE
Crossover 22.0.1

### ISSUE THREAD

**Issue by imanel** [Gcenx/homebrew-wine#65]
Hey! First things first - amazing work with all the packages!

I noticed that, despite being released a while ago, Crossover 22 is not yet available via Homebrew packages. Are there any plans for releasing it? Let me know if I can help in any way.

**Comment by Gcenx** [comment]
Theses a number of caveats to providing an updated `wine-crossover` Cask.

- Doesn’t support creating 32Bit prefixes
- Upstream winetricks won’t work (awaiting a merge)
- unknown amount of regressions

I’ve not yet published WineCX22.0.1 based engine for Wineskins due to the above, this also doesn’t take into the account the amount of bugs we’ve seen in XiV on Mac.

**Comment by imanel** [comment]
> Doesn’t support creating 32Bit prefixes
Do you mean 32Bit or wine32on64? I thought that the whole point of Crossover implementation was to provide wine32on64 for newer Macs.

**Comment by Gcenx** [comment]
> Do you mean 32Bit or wine32on64? I thought that the whole point of Crossover implementation was to provide wine32on64 for newer Macs.

CX19 > CX21.2.0 could create a “32Bit” only wineprefix allowing somethings that won’t run within the more standard “wow64” wineprefix to function.

CX22 also doesn’t actually make use of `wine32on64` it only uses `wine64` even when launching 32Bit binaries.

CrossOver itself creates “bottles” using another utility’s not `wineboot` that’s what it can generate 32Bit wineprefixes still even on macOS Catalina and later.
