### ISSUE TITLE
Unable to downgrade to wine 5.0

### ISSUE THREAD

**Issue by DiskPoppy** [Gcenx/homebrew-wine#76]
I wish to downgrade to wine 6, which I had previously installed. I tried to use an older formula, however https://github.com/Gcenx/homebrew-wine/releases/download/20.0.2/wine-crossover-20.0.2-osx64.tar.xz returns 404.

**Comment by Gcenx** [comment]
The archive url you’ve posted is for 20.0.2 that’s not wine-6.0 and was also removed March 3rd https://github.com/Gcenx/homebrew-wine/commit/bbbe0129157cc22bbad8a7f70ba9ee57323f525d

From an Intel brew install run;
```
brew install --formula gcenx/wine/wine-crossover
```
This formula currently _doesn’t_ handle mapping wine32on64 > wine however in open to a PR to resolve this.

**Comment by DiskPoppy** [comment]
I tried that, and it installed wine-7.0.

**Comment by Gcenx** [comment]
Here’s direct urls to both the cask and foruma as can be seen the formula is 21.2.0 where as the cask is 22.0.1

https://github.com/Gcenx/homebrew-wine/blob/2dede5c30047fd35cefc0bd4598f50f9abee1a28/Casks/wine-crossover.rb#L2-L5

https://github.com/Gcenx/homebrew-wine/blob/2dede5c30047fd35cefc0bd4598f50f9abee1a28/Formula/wine-crossover.rb#L4

The only time I could see the cask being installed is if the command was ram via /opt/homebrew/bin/brew instead of /usr/local/bin/brew aka the Intel brew instal requirement.

**Comment by DiskPoppy** [comment]
Oops, what I meant was wine 5.0. There seems to be no way to downgrade to that version.

**Comment by Gcenx** [comment]
So your really looking for a wine-crossover-20.0.4 based build, this should still be buildable I’d think I could copy/paste the current formula and slightly tweak it.

**Comment by Gcenx** [comment]
If possible please test #77

**Comment by DiskPoppy** [comment]
It works, though it appears to configure and `make` twice, not sure if it is intended.

**Comment by Gcenx** [comment]
> It works

Are you referring to it building or did you also verify running something against this keg-only build (you’ll have wine64 and wine32on64 binary’s within the kegs /bin directory)

 > though it appears to configure and `make` twice, not sure if it is intended

That’s intentional as wine64 and wine32on64 need to be configured/built/installed separately.

**Comment by DiskPoppy** [comment]
It built and I tried running some Windows programs.

**Comment by Gcenx** [comment]
Reopening as I’ve not yet merged the formula

**Comment by Gcenx** [comment]
Need to add the relevant wine-gecko msi installers then I’ll merge the PR so it will have a bottle
